# Site Settings
title: Get over it!
email: lgy605555@gmail.com
description: Developer.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://lgy0920.github.io" # the base hostname & protocol for your site
google_analytics: "UA-122078780-1"

# User Settings
username: Gil-Yong LEE
user_description: S/W Developer.
disqus_username:  Gil-Yong LEE

# Social Media
# Remove the item if you don't need it
github_username: lgy0920
facebook_username: 100001786382768
# twitter_username: twitter_username
instagram_username: gily.leeeeee
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-slate